
sudo: false
language: generic

env:
    global:
        - COMMIT_AUTHOR_EMAIL: b.f.van.beek@vu.nl

matrix:
    include:
        - os: linux
          env: PYTHON_VERSION=3.7 MINICONDA=Linux-x86_64.sh
        - os: linux
          env: PYTHON_VERSION=3.8 MINICONDA=Linux-x86_64.sh
        - os: osx
          env: PYTHON_VERSION=3.7 MINICONDA=MacOSX-x86_64.sh
        - os: osx
          env: PYTHON_VERSION=3.8 MINICONDA=MacOSX-x86_64.sh

install:
    # Install python
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-${MINICONDA} -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no --set auto_update_conda False
    - conda update -q conda

    # Useful for debugging any issues with conda
    - conda info -a

    # Install the package
    - conda create -n FOX python=${PYTHON_VERSION}
    - conda install -n FOX -y -c conda-forge h5py rdkit
    - source activate FOX
    - pip install .[test]

script:
    # Run the unitary tests excluding the expensive computations
    - pytest -m "not (slow or long)" --cov-config .coveragerc --cov=FOX tests
    - coverage xml && coverage report -m

branches:
    only:
        - master
        - Auto-FOX-0.8
