
sudo: false
language: none
rvm:
  - 

env:
  global:
    - COMMIT_AUTHOR_EMAIL: "b.f.van.beek@vu.nl"
  matrix:
    - PYTHON_VERSION=3.0
    - PYTHON_VERSION=3.1
    - PYTHON_VERSION=3.2
    - PYTHON_VERSION=3.3
    - PYTHON_VERSION=3.4
    - PYTHON_VERSION=3.5
    - PYTHON_VERSION=3.6
    - PYTHON_VERSION=3.7

install:
  # Install python
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda False
  - conda update -q conda
  
  # Useful for debugging any issues with conda
  - conda info -a
  
  # Install the package
  - conda install -y -c conda-forge h5py
  - pip install .[test]
  
script:
  # Run the unitary tests excluding the expensive computations
  - pytest -m "not (slow or long)" --cov-config .coveragerc --cov=FOX tests
  - coverage xml && coverage report -m

branches:
  only:
  - master
